[tox]
envlist=
    py{310,311,312,313,313t,314,314t}-{ens,core,lint,wheel}
    py{310,311,312,313,313t,314,314t}-integration-{goethereum,ethtester}
    docs
    benchmark
    windows-wheel

[flake8]
exclude= venv*,.tox,docs,build
extend-ignore=E203,W503
max-line-length=88
per-file-ignores=__init__.py:F401

[blocklint]
max_issue_threshold=1

[testenv]
allowlist_externals=make,pre-commit
changedir={envtmpdir}
install_command=python -m pip install {opts} {packages}
package=wheel
extras = test
commands=
    core: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/core -n auto --maxprocesses=15}
    core_sync: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/core -m "not asyncio" -n auto --maxprocesses=15}
    core_async: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/core -m asyncio -n auto --maxprocesses=15}
    ens: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/ens -n auto --maxprocesses=15}
    ens-lite: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/ens --ignore={toxinidir}/tests/ens/normalization/test_normalize_name_ensip15.py -n auto --maxprocesses=15}
    ensip15: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/ens/normalization/test_normalize_name_ensip15.py -q -n auto --maxprocesses=15}
    integration-goethereum-ipc: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/integration/go_ethereum/test_goethereum_ipc.py -k "not Async" -n auto --maxprocesses=15}
    integration-goethereum-ipc_async: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/integration/go_ethereum/test_goethereum_ipc.py -k Async -n auto --maxprocesses=15}
    integration-goethereum-http: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/integration/go_ethereum/test_goethereum_http.py -k "not Async" -n auto --maxprocesses=15}
    integration-goethereum-http_async: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/integration/go_ethereum/test_goethereum_http.py -k Async -n auto --maxprocesses=15}
    integration-goethereum-legacy_ws: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/integration/go_ethereum/test_goethereum_legacy_ws.py -n auto --maxprocesses=15}
    integration-goethereum-ws: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/integration/go_ethereum/test_goethereum_ws -n auto --maxprocesses=15}
    integration-goethereum: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/integration/go_ethereum -n auto --maxprocesses=15}
    integration-ethtester: python -I {toxinidir}/scripts/pytest_installed_wheel.py --repo-root {toxinidir} -- {posargs:{toxinidir}/tests/integration/test_ethereum_tester.py -n auto --maxprocesses=15}
    docs: make check-docs-ci
passenv =
    GETH_BINARY
    GOROOT
    GOPATH
    WEB3_INFURA_PROJECT_ID
    WEB3_INFURA_API_SECRET
basepython =
    docs: python
    windows-wheel: python

[testenv:docs]
changedir={toxinidir}
deps =
    .[test,docs]
commands =
    make check-docs-ci

[testenv:py{310,311,312,313,313t,314,314t}-lint]
changedir={toxinidir}
deps=pre-commit
extras=dev
commands=
    pre-commit install
    pre-commit run --all-files --show-diff-on-failure

[testenv:benchmark]
basepython=python
changedir={toxinidir}
commands=
    python {toxinidir}/web3/tools/benchmark/main.py --num-calls 5
    python {toxinidir}/web3/tools/benchmark/main.py --num-calls 50
    python {toxinidir}/web3/tools/benchmark/main.py --num-calls 100


[testenv:py{310,311,312,313,313t,314,314t}-wheel]
changedir={toxinidir}
deps=
    wheel
    build[virtualenv]
allowlist_externals=
    /bin/rm
    /bin/bash
commands=
    /bin/bash {toxinidir}/faster_web3/scripts/release/test_wheel_install.sh
skip_install=true

[testenv:windows-wheel]
changedir={toxinidir}
deps=
    wheel
    build[virtualenv]
allowlist_externals=
    bash.exe
commands=
    bash.exe {toxinidir}/faster_web3/scripts/release/test_windows_wheel_install.sh
skip_install=true
