name: CodSpeed Benchmarks

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Run CodSpeed Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] pytest-codspeed web3
      - name: Remove Python files from test env
        run: |
          rm -r faster_web3
          rm -r faster_ens
      - name: Run CodSpeed
        uses: CodSpeedHQ/action@v3
        with:
          run: pytest --codspeed -k "test_faster_" benchmarks/
